---
title: "Untitled"
author: "Nazmul haque"
date: "2024-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::oppts_chunk$set(echo = TRUE)
```

##################

```{r}
v2 =h.like.model2$lambda.0
v2 = as.data.frame(v2)
v2$time = as.numeric(rownames(v2))
times <- v2$time

baseline_hazards2 <- v2$X1


```

```{r}
#divisions
betad2<-h.like.model2$beta$Estimate[8]
betad3<-h.like.model2$beta$Estimate[9]
betad4<-h.like.model2$beta$Estimate[10]
betad5<-h.like.model2$beta$Estimate[11]
betad6<-h.like.model2$beta$Estimate[12]
betad7<-h.like.model2$beta$Estimate[13]
betad8<-h.like.model2$beta$Estimate[14]

cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))
cumulative_hazards_3 <- numeric(length(times))
cumulative_hazards_4 <- numeric(length(times))
cumulative_hazards_5 <- numeric(length(times))
cumulative_hazards_6 <- numeric(length(times))
cumulative_hazards_7 <- numeric(length(times))
cumulative_hazards_8 <- numeric(length(times))
cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))
cif_3 <- numeric(length(times))
cif_4 <- numeric(length(times))
cif_5 <- numeric(length(times))
cif_6 <- numeric(length(times))
cif_7 <- numeric(length(times))
cif_8 <- numeric(length(times))

for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))
  cumulative_hazards_3[i] <- sum(baseline_hazards2[1:i] * exp(betad3))
  cumulative_hazards_4[i] <- sum(baseline_hazards2[1:i] * exp(betad4))
  cumulative_hazards_5[i] <- sum(baseline_hazards2[1:i] * exp(betad5))
  cumulative_hazards_6[i] <- sum(baseline_hazards2[1:i] * exp(betad6))
  cumulative_hazards_7[i] <- sum(baseline_hazards2[1:i] * exp(betad7))
  cumulative_hazards_8[i] <- sum(baseline_hazards2[1:i] * exp(betad8))

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])
  cif_3[i] <- 1 - exp(-cumulative_hazards_3[i])
  cif_4[i] <- 1 - exp(-cumulative_hazards_4[i])
  cif_5[i] <- 1 - exp(-cumulative_hazards_5[i])
  cif_6[i] <- 1 - exp(-cumulative_hazards_6[i])
  cif_7[i] <- 1 - exp(-cumulative_hazards_7[i])
  cif_8[i] <- 1 - exp(-cumulative_hazards_8[i])

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2,
  CIF_3 = cif_3,
  CIF_4 = cif_4,
  CIF_5 = cif_5,
  CIF_6 = cif_6,
  CIF_7 = cif_7,
  CIF_8 = cif_8
)

library(ggplot2)

ppt1 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "Barishal"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Chattogram"), size = 1.2) +  
  geom_line(aes(y = CIF_3, color = "Dhaka"), size = 1.2) +
  geom_line(aes(y = CIF_4, color = "Khulna"), size = 1.2) +
  geom_line(aes(y = CIF_5, color = "Rajshahi"), size = 1.2) +
  geom_line(aes(y = CIF_6, color = "Rangpur"), size = 1.2) +
  geom_line(aes(y = CIF_7, color = "Mymensingh"), size = 1.2) +
  geom_line(aes(y = CIF_8, color = "Sylhet"), size = 1.2) +

  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Divisions", 
                     values = c("Barishal" = "#9B0000",   # Dark Red
                                "Chattogram" = "#123979",           # Navy Blue
                                "Dhaka" = "#006400",                # Dark Green
                                "Khulna" = "#8B0082",               # Dark Purple
                                "Rajshahi" = "#FF5C00",             # Dark Orange
                                "Rangpur" = "green",              # Teal
                                "Mymensingh" = "blue",           # Brown
                                "Sylhet" = "black"))  +

  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

```
```{r}
# Save the plot
ggsave(filename = "D:\\survival paper\\graph\\divisionsnon.png",  # Specify the file name
       plot = ppt1,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300)                                     # Set the resolution (dots per inch)

```

```{r}
#medu
betad2<-h.like.model2$beta$Estimate[15]
betad3<-h.like.model2$beta$Estimate[16]
betad4<-h.like.model2$beta$Estimate[17]


cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))
cumulative_hazards_3 <- numeric(length(times))
cumulative_hazards_4 <- numeric(length(times))


cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))
cif_3 <- numeric(length(times))
cif_4 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))
  cumulative_hazards_3[i] <- sum(baseline_hazards2[1:i] * exp(betad3))
  cumulative_hazards_4[i] <- sum(baseline_hazards2[1:i] * exp(betad4))
  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])
  cif_3[i] <- 1 - exp(-cumulative_hazards_3[i])
  cif_4[i] <- 1 - exp(-cumulative_hazards_4[i])
  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2,
  CIF_3 = cif_3,
  CIF_4 = cif_4
)

library(ggplot2)

ppt2 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "No Education"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Primary"), size = 1.2) +  
  geom_line(aes(y = CIF_3, color = "Secondary"), size = 1.2) +
  geom_line(aes(y = CIF_4, color = "Higher"), size = 1.2) +
  

  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Mother Education", 
                     values = c("No Education" = "#9B0000",   # Dark Red
                                "Primary" = "blue",           # Navy Blue
                                "Secondary" = "green",                # Dark Green
                                "Higher" = "#8B0082")) +

  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\Medunon.png",  # Specify the file name
       plot = ppt2,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 

```

```{r}
#wealth
betad2<-h.like.model2$beta$Estimate[18]
betad3<-h.like.model2$beta$Estimate[19]



cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))
cumulative_hazards_3 <- numeric(length(times))


cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))
cif_3 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))
  cumulative_hazards_3[i] <- sum(baseline_hazards2[1:i] * exp(betad3))
  
  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])
  cif_3[i] <- 1 - exp(-cumulative_hazards_3[i])
  
  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2,
  CIF_3 = cif_3
)

library(ggplot2)

ppt3 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "Poor"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Middle"), size = 1.2) +  
  geom_line(aes(y = CIF_3, color = "Rich"), size = 1.2) +


  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Wealth Status", 
                     values = c("Poor" = "darkgreen",   # Dark Red
                                "Middle" = "blue",           # Navy Blue
                                "Rich" = "#FF5C00")) +                # Dark Green
  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\wealthnon.png",  # Specify the file name
       plot = ppt3,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 
```

```{r}
#fedu
betad2<-h.like.model2$beta$Estimate[20]
betad3<-h.like.model2$beta$Estimate[21]
betad4<-h.like.model2$beta$Estimate[22]
betad5<-h.like.model2$beta$Estimate[23]


cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))
cumulative_hazards_3 <- numeric(length(times))
cumulative_hazards_4 <- numeric(length(times))
cumulative_hazards_5 <- numeric(length(times))

cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))
cif_3 <- numeric(length(times))
cif_4 <- numeric(length(times))
cif_5 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))
  cumulative_hazards_3[i] <- sum(baseline_hazards2[1:i] * exp(betad3))
  cumulative_hazards_4[i] <- sum(baseline_hazards2[1:i] * exp(betad4))
  cumulative_hazards_5[i] <- sum(baseline_hazards2[1:i] * exp(betad5))
  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])
  cif_3[i] <- 1 - exp(-cumulative_hazards_3[i])
  cif_4[i] <- 1 - exp(-cumulative_hazards_4[i])
  cif_5[i] <- 1 - exp(-cumulative_hazards_5[i])
  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2,
  CIF_3 = cif_3,
  CIF_4 = cif_4,
  CIF_5 = cif_5
)

library(ggplot2)

ppt4 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "No Education"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Primary"), size = 1.2) +  
  geom_line(aes(y = CIF_3, color = "Secondary"), size = 1.2) +
  geom_line(aes(y = CIF_4, color = "Higher"), size = 1.2) +
  geom_line(aes(y = CIF_5, color = "Others"), size = 1.2) +
  

  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Father Education", 
                     values = c("No Educatio" = "#9B0000",   # Dark Red
                                "Primary" = "#123979",           # Navy Blue
                                "Secondary" = "#006400",                # Dark Green
                                "Higher" = "#8B0082",               # Dark Purple
                                "Others" = "#FF5C00"))  +

  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\fedunon.png",  # Specify the file name
       plot = ppt4,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 

```

```{r}
#R/U
betad2<-h.like.model2$beta$Estimate[24]



cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))


cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))

  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])

  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2)

library(ggplot2)

ppt5 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "Rural"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Urban"), size = 1.2) +  

  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Place of Residence", 
                     values = c("Rural" = "#FF5C00",   # Dark Red
                                "Urban" = "blue")) +                # Dark Green
  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\v025non.png",  # Specify the file name
       plot = ppt5,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 
```
```{r}
#religion
betad2<-h.like.model2$beta$Estimate[25]



cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))


cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))

  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])

  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2)

library(ggplot2)

ppt6 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "Others"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Islam"), size = 1.2) +  

  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Religion", 
                     values = c("Others" = "#FF5C00",   # Dark Red
                                "Islam" = "blue")) +                # Dark Green
  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\Religionnon.png",  # Specify the file name
       plot = ppt6,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 
```

```{r}
#mother age
betad2<-h.like.model2$beta$Estimate[1]
betad3<-h.like.model2$beta$Estimate[2]



cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))
cumulative_hazards_3 <- numeric(length(times))


cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))
cif_3 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))
  cumulative_hazards_3[i] <- sum(baseline_hazards2[1:i] * exp(betad3))
  
  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])
  cif_3[i] <- 1 - exp(-cumulative_hazards_3[i])
  
  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2,
  CIF_3 = cif_3
)

library(ggplot2)

ppt7 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "20-30"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "<20"), size = 1.2) +  
  geom_line(aes(y = CIF_3, color = ">30"), size = 1.2) +


  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Mother Age", 
                     values = c("20-30" = "darkgreen",   # Dark Red
                                "<20" = "blue",           # Navy Blue
                                ">30" = "#FF5C00")) +                # Dark Green
  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\motheragenon.png",  # Specify the file name
       plot = ppt7,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 
```
```{r}
#gender
betad2<-h.like.model2$beta$Estimate[3]



cumulative_hazards_0 <- numeric(length(times))
cumulative_hazards_2 <- numeric(length(times))


cif_0 <- numeric(length(times))
cif_2 <- numeric(length(times))


for (i in 1:length(times)) {
  cumulative_hazards_0[i] <- sum(baseline_hazards2[1:i])
  cumulative_hazards_2[i] <- sum(baseline_hazards2[1:i] * exp(betad2))

  

  cif_0[i] <- 1 - exp(-cumulative_hazards_0[i])
  cif_2[i] <- 1 - exp(-cumulative_hazards_2[i])

  

}

cif_data <- data.frame(
  time = times,
  CIF_0 = cif_0,
  CIF_2 = cif_2)

library(ggplot2)

ppt8 = ggplot(cif_data, aes(x = time)) +
  geom_line(aes(y = CIF_0, color = "Male"), size = 1.2) +
  geom_line(aes(y = CIF_2, color = "Female"), size = 1.2) +  

  labs(title = "Cumulative Incidence Function (CIF) For Non-disease",
       x = "Time (days)",
       y = "Cumulative Incidence Function (CIF)") +
  
  scale_color_manual(name = "Sex of Child", 
                     values = c("Male" = "#FF5C00",   # Dark Red
                                "Female" = "blue")) +                # Dark Green
  theme_survminer() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.position = "top",   # Move the legend to the top of the plot
        legend.title = element_text(size = 12, face = "bold", hjust = 0.5),  # Center legend title
        legend.text = element_text(size = 10),  # Adjust legend text font
        axis.title.x = element_text(size = 12, face = "bold"),  # Adjust x-axis label font
        axis.title.y = element_text(size = 12, face = "bold"),  # Adjust y-axis label font
        axis.text = element_text(size = 10)) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

ggsave(filename = "D:\\survival paper\\graph\\gendernon.png",  # Specify the file name
       plot = ppt8,                                      # Specify the plot object
       width = 10,                                     # Set the width of the output file (in inches)
       height = 6,                                    # Set the height of the output file (in inches)
       dpi = 300) 
```

